FROM node:latest

ENV NODE_ENV=development
# LABEL version="1.0"
LABEL description="Development image for the Portfolio api"

WORKDIR /app
COPY package.json ./

COPY yarn.lock ./

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD ["sh","-c", "npm run dev"]
